### ISSUE TITLE
When Date.now() is used as x value line chart doesn't show

### ISSUE THREAD

**Issue by Kagrra** [huww98/TimeChart#11]
Loving your work, but I can't get Date.now() passed as x value to work.

Smaller numbers works fine, performance.now() also works, but with Date.now() there is no line. 

What is interesting is that this code does not work:
```
var time: number = Date.now();
for (var i: number = 0; i < 10000; i++) {
  chart_data.push({ x: time + i, y: i });
}
```
But this one renders properly:
```
var time: number = Date.now()\10000;
for (var i: number = 0; i < 10000; i++) {
  chart_data.push({ x: time*i, y: i });
}
```

**Comment by huww98** [comment]
That is because I use single-precision floating-point numbers to upload data to GPU. The precision is not enough to store the exact value of `Date.now()`

You may try this:

```javascript
let time = Date.now();
let arr = new Float32Array([time, time + 1])
console.log(arr[0] === arr[1])
```

Very likely the output is true. And this violates the requirement in README: "The x value of each data point must be monotonically increasing"

This is the reason I introduce the option `baseTime`. You should set `baseTime` to `Date.now()` when creating the chart, then substract each x value by that value to make it smaller.

**Comment by huww98** [comment]
BTW, maybe you should record a timestamp when you record your data. `Date.now()` can be inaccurate due to network latency, unless your data is just generated from the browser.

**Comment by Kagrra** [comment]
Thanks a lot! I did not understand `baseTime` and wasn't substracting base value from current time. Works like a charm now.
