### ISSUE TITLE
Avoid drawing series over Y axis padding area

### ISSUE THREAD

**Issue by debevv** [huww98/TimeChart#24]
Hi, is there a way to disable drawing in the padding area? If not, can you point me where I should start to edit the code?
Thank you

**Comment by huww98** [comment]
> Hi, is there a way to disable drawing in the padding area?

No. I'm intended to make the viewport as large as possible.

> If not, can you point me where I should start to edit the code?

There has been some time since I wrote these codes. As best as I can remember: You need to adjust the canvas positioning

https://github.com/huww98/TimeChart/blob/70c5060cc827080799a427603a04e453f23613c1/src/canvasLayer.ts#L27

Adjust the rendered domain (should be optional, change this should give you a little better performance)

https://github.com/huww98/TimeChart/blob/70c5060cc827080799a427603a04e453f23613c1/src/lineChartRenderer.ts#L393-L396

Adjust how to calculate the origin point coordination.

https://github.com/huww98/TimeChart/blob/70c5060cc827080799a427603a04e453f23613c1/src/lineChartRenderer.ts#L419

**Comment by huww98** [comment]
`renderPadding*` options are added in 1.0.0-beta.5. Please try it out. Or you can preview this feature at https://huww98.github.io/TimeChart/demo/

**Comment by terjew** [comment]
Tested the preview now, looks great!
