### ISSUE TITLE
Prepending data

### ISSUE THREAD

**Issue by sleighsoft** [huww98/TimeChart#8]
Is it possible or can you guide me on how I could prepend data to a trace instead of appending it?

Any help is greatly appreciated :)

**Comment by huww98** [comment]
You cannot prepend data currently, and it would be non-trivial to implement that.

Why do you want to prepend data, since the X-axis always represents time in this library? Maybe you want a right-to-left layout?

**Comment by sleighsoft** [comment]
I would like to load a particular slice of timing data and when panning left and right load and add additional timing data from either before or after. Ideally I would also be able to unload part of the timing data if whatever is currently loaded exceeds a memory limit.

**Comment by Venryx** [comment]
I have the same request and a similar use-case: My program lets the user review eeg-data from a whole night of sleeping, from a device that records 512 values per second. For 8 hours of sleep, this means: `512*60*60*8 = 14,745,600 values`

Even if TimeChart can handle loading that many values all at once, the problem is that I also need to perform processing on those values before displaying them (normalization, smoothing, and adding of two additional lines for derivative values), and this processing takes a significant amount of time.

I therefore want to apply the processing only for slices of the data that the user is currently viewing. Since the user may start viewing a section of data in the middle, this means the charting library would need to either support prepending data, or editing entry values.

If prepending data is too difficult, would adding support for data-point editing be easier?

That functionality would open up two solutions:
1) Start by sending it an array for the whole night, but filled with simple 0s -- and as the user pans to different areas, I replace those 0s with the actual raw and processed values. This avoids calling the heavy processing code for sections of the night data not yet panned to, and should be sufficient so long as TimeChart can handle being sent an initial array of ~10 million zeroes.
2) Send TimeChart a small array, with, say, one data-point per pixel of the chart width. Then, as the user pans (I guess this would be handled by custom code rather than TimeChart), we dynamically update the ~1000 entries' values to reflect the slice of data currently panned to. [Here is a demo](https://codesandbox.io/s/webgl-plot-react-forked-l2214?file=/src/webglAppSin.tsx) of this in [webgl-plot](https://github.com/danchitnis/webgl-plot). (use the "Reverse" checkbox to toggle between "panning" left and right)

I would consider just using webgl-plot, since the demo has the entry-editing functionality I need; however, the major drawback is that webgl-plot appears to have no grid/axes rendering, which is an important aspect for my use-case.

**Comment by huww98** [comment]
I'm considering using [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to capture the changes to the data array so that every change you do to the data array will be reflected on the chart. [Vue3](https://vuejs.org/) uses the same technique to detect changes in data and sync them to view.

But now I'm busy with my school works. I only have time to implement this after 1 or 2 weeks.

**Comment by Venryx** [comment]
Well, the benchmark there [is using the WebGL renderer](https://github.com/leeoniya/uPlot/blob/master/bench/Plotly.js.html#L78) -- which is faster per line rendered, but apparently isn't compatible with freeform array modifications. (when I switch to "scattergl" in my demo, the chart goes blank after pressing the "Extend data" button)

If the benchmark was using Plotly in SVG-renderer mode, it would still definitely slower than uPlot, webgl-plot, and TimeChart in terms of render-time per line. However, because svg-mode Plotly comes with that data decimator/simplifier system (based on current pan/zoom), it's able to give great performance, but without as many restrictions. (eg. it lets you add and edit entries at will)

Anyway, the best scenario would be a library that combines webgl-rendering with a solid data decimation/simplifier system; but in the meantime, Plotly (in SVG mode, with that option enabled) gets the job done.

**Comment by huww98** [comment]
I personally don't like a universal data simplifier system. If you have more data points than your monitor resolution, you can set the line width to less than 1 pixels, and get details from rendered pixel opacity.

In the meantime, a domain-specific simplifier can be useful. For example, show the average value in each hour, and inform the end-user how these values are calculated.

**Comment by leeoniya** [comment]
@Venryx i would be interested to see how your dataset & use-case performs in uPlot. avoiding svg is a pretty straightforward win, but using webgl instead of plain canvas2d does not have the same cleat benefit. for non-streaming, data exploration type cases, canvas2d is often the better choice.

**Comment by Venryx** [comment]
@leeoniya Yes, I've been considering uPlot. The main reason I'm going with Plotly for now is that the smoothness of the panning/scrolling is just so good. uPlot isn't bad either, but it's not quite as smooth as Plotly (with its data-decimation option on).

Compare:
1) uPlot (animation presumably equivalent to panning): https://leeoniya.github.io/uPlot/demos/stream-data.html
2) Plotly, with data-decimation (use pan tool): https://codepen.io/Venryx/pen/eYzpEzN

uPlot isn't bad, and is probably workable in my app, but the extra smoothness of Plotly is noticeable. Of course, since it's accomplishing that smoothness merely through data-decimation, it should be transferable to the other charting libraries. However, from what I understand, few of them have such an option integrated. (or if they do, they are half-baked, such as [the one for chartjs](https://github.com/AlbinoDrought/chartjs-plugin-downsample), which I never got to work right)

**Comment by leeoniya** [comment]
the jumpiness is due to the data being updated & re-redered at 100ms intervals, not a perf limitation:

https://github.com/leeoniya/uPlot/blob/6ac8f395119ad5ee2eaf31932ab30027bb7025a4/demos/stream-data.html#L64

there's also no animation/transition support in uPlot, which i guess doesn't help the situation, but it's not a perf issue.

the plotly demo uses a hard-coded `[-1000, 1000]` y range, while uPlot has to re-find it for each series on each data update. you can config uPlot to avoid this overhead as well, though it's not enormous. anyways, the two examples are pretty apple-to-oranges, while the bench i linked is more apples-to-apples.

**Comment by Venryx** [comment]
Okay, that's good to hear; I'll likely give uPlot a try, if I hit significant annoyances or perf-issues while trialing Plotly.

By the way, it would be nice if the uPlot demos had some way for users to modify/sandbox them (a simple link to a codesandbox equivalent would suffice).

That's something I've grown accustomed to when trying out libraries (especially for things like charting libraries, where there are literally hundreds of options), so when a site has demos that I can't edit, it makes me hesitant to evaluate them as closely. (for example, I might have noticed the 100ms update interval that way)

**Comment by leeoniya** [comment]
> a simple link to a codesandbox equivalent, for example).

i prefer to keep all the demo code locally and not rely on third party services and keep external demos updated. i might do something like what i did with domvm in the future, though: https://domvm.github.io/domvm/demos/. i've been waiting on CodeMirror 6 to becomes table first, though and i'm currently blocked on https://github.com/codemirror/codemirror.next/issues/284.

> By the way, I just took the time to figure out how to use "Local Overrides" in the Chrome dev-tools: https://www.afasterweb.com/2018/04/19/using-local-overrides-in-devtools

that's pretty neat.

> Anyway, I was thus able to try changing the interval to 10ms

anything less than 16.6666ms is pure waste, since that's a 60fps frame :) you're better off scheduling data updates via `requestAnimationFrame()`

**Comment by leeoniya** [comment]
> Anyway, I think your readme page comment on panning is too modest:

under-promise, over-deliver :D

**Comment by Venryx** [comment]
> under-promise, over-deliver :D

Okay, but you should link to a demo page showing off your under-promise, over-delivering then. :)

For example, uPlot is just as responsive as the Plotly demo now:
Plotly: https://codepen.io/Venryx/pen/eYzpEzN
uPlot: https://codepen.io/Venryx/pen/vYKNdZw

I wouldn't have expected that based on the readme contents. :)

**Comment by Venryx** [comment]
Also, I should probably stop spamming the TimeChart issue with uPlot-related information. XD

I made a new thread for it here: https://github.com/leeoniya/uPlot/issues/329

I'll add further uPlot-related comments there from now on. (sorry, @huww98!)

**Comment by huww98** [comment]
That's OK. 

I have a look at Plotly. it uses a clever strategy to handle user interaction. It just transforms the whole plot in response to the `wheel` event. and rerender the plot only once after the user interaction finished. By contrast, TimeChart rerenders every data point at every frame. I have to admit that although this strategy is not perfect, it works well enough.

**Comment by sleighsoft** [comment]
@Venryx I know Plotly, I added the prependData feature to its python backend a couple of weeks ago ;)
